import type { Metadata } from 'next'
import './globals.css'
import { Bowlby_One_SC, DM_Mono } from 'next/font/google'

const bowldy = Bowlby_One_SC({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-bowlbt-sc',
    weight: '400',
})

const dmMono = DM_Mono({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-dm-mono',
    weight: '500',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${bowldy.variable} ${dmMono.variable} antialiased font-mono font-medium text-zink-800`}>
                {children}
            </body>
        </html>
    )
}
